<?php
/**
 * @var \Bss\Faq\Block\Category\Category $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $faqByCategory = $block->getFaqListByCategory(); ?>
<div class="bss-faq-collection">
    <div class="collspan-expand-block">
        <a href="#" id="collapse-faqs">
            <?= $escaper->escapeHtml(__('Collapse All')) ?>
        </a> |
        <a href="#" id="expand-faqs">
            <?= $escaper->escapeHtml(__('Expand All')) ?>
        </a>
    </div>

    <div id="faq-content" class="faq-content">
        <?php if (!empty($faqByCategory)): ?>
                <div id="group">
                    <div class="group-title">
                        <?= $escaper->escapeHtml('.') ?>
                    </div>
                    <?php foreach ($faqByCategory as $categoryData): ?>
                    <div class="faq-accordion">
                        <h3><?= $escaper->escapeHtml($categoryData->getTitle()) ?></h3>
                        <div>
                            <p><?= $block->filterOutputHtml($categoryData->getContent()) ?></p>
                            <a href="<?=
                            $escaper->escapeHtml($block->getFaqDetailUrl($categoryData->getId())) ?>">Read more</a>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
        <?php endif; ?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom faq-paginate"><?= $block->getPagerHtml(); ?></div>
        <?php endif ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_Faq/js/faq": {
                "page_type" : "scroll"
            }
        }
    }
</script>
