<?php
/**
 * @var \Bss\Faq\Block\Detail\Detail $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="faq-content">
    <?php $faq = $block->getFaqData()?>
    <h1><?= $escaper->escapeHtml($faq->getTitle()) ?></h1>
    <div class="details">
        <div class="created-by">
            <span class="author">
                <i class="faq-iconuser"></i>
                <?= $escaper->escapeHtml(__('Created by') . ' ' . $faq->getCreatedBy() . ' |') ?>
            </span>
            <span class="calendar">
                <i class="faq-iconcalendar"></i>
                <?= $escaper->escapeHtml($faq->getCreatedAt() . ' |')?>
            </span>
            <span class="category">
                <?= $escaper->escapeHtml($block->getFaqCategoryTitle($faq->getCategoryId())) . ' |' ?>
            </span>
            <span class="viewed">
                <i class="faq-iconeye"></i>
                <?= $escaper->escapeHtml($faq->getView()) ?>
            </span>
        </div>
        <p class="content"><?= $block->filterOutputHtml($faq->getContent()) ?></p>
        <div class="feedback" id="feedback">
            <div class="hidden" id="BASE_URL"><?= $escaper->escapeHtml($block->getAjaxUrl()) ?></div>
            <div class="hidden" id="message"><?=
                $escaper->escapeHtml('Glad to hear it — Thanks for the feedback'); ?></div>
            <button class="btn" id="btn-like">
                <span class="faq-iconhappy"></span>
                <span><?= $escaper->escapeHtml(__('Yes')) ?></span>
            </button>
            <button class="btn" id="btn-dislike">
                <span class="faq-iconangry"></span>
                <span><?= $escaper->escapeHtml(__('No')) ?></span>
            </button>
        </div>
    </div>
</div>

