<?php
/**
 * @var \Bss\Faq\Block\Search\SearchForm $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="faq-search-form">
    <div class="content">
        <form class="form"
              action="<?= $escaper->escapeHtml(__("https://magento247.test/faq/search")) ?>"
              id="faq-search-form"
              method="get"
              data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <div class="field">
                <div class="control">
                    <input name="s"
                           type="text"
                           id="text-search"
                           placeholder="<?= $escaper->escapeHtml(__('* Search Frequently Asked Question')) ?>"
                           data-validate="{required:true}"
                           value="<?= $escaper->escapeHtml($block->getTextSearch()) ?>">
                </div>
            </div>
            <div class="actions">
                <button class="action primary" title="" type="submit">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
